#!/bin/bash

# List files in the current directory in long format
ls -la

# List files in the parent directory in long format
ls -la ..

# List files in the /boot directory in long format
ls -la /boot

